/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enrollmentsystem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rochelle D. Abella
 */
public class AdminDashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName());

    /**
     * Creates new form AdminDashboardFrame
     */
    public AdminDashboardFrame() {
        initComponents();
        initializeStudentTable();
        loadStudentData();    
//        loadProgramTable();
    }
    
    DefaultTableModel studentModel;
    
    private void initializeStudentTable() {studentModel =
            (DefaultTableModel) tblStudents.getModel();
}

    private void loadStudentData() {
    // CLEAR TABLE FIRST
    studentModel.setRowCount(0);
    // ADD STUDENT DATA
    studentModel.addRow(new Object[] {
        "2026-1001",
        DataStore.fullName,
        DataStore.firstChoice,
        "SET A",
        "PENDING"
    });
}
//    
//    // =====================================================
//// SLOT VARIABLES
//// =====================================================
//
//int bsitSetA = 2;
//int bsitSetB = 2;
//
//int bsisSetA = 2;
//int bsisSetB = 2;
//
//int entSetA = 2;
//int entSetB = 2;
//
//int bsedMathSetA = 2;
//int bsedMathSetB = 2;
//
//private void loadProgramTable() {
//
//    DefaultTableModel model =
//            (DefaultTableModel)
//                    tblProgram.getModel();
//
//    // CLEAR TABLE
//    model.setRowCount(0);
//
//    // =====================================================
//    // BSIT
//    // =====================================================
//
//    model.addRow(new Object[] {
//        "BSIT",
//        "Institute of Computing",
//        "SET A",
//        bsitSetA
//    });
//
//    model.addRow(new Object[] {
//        "BSIT",
//        "Institute of Computing",
//        "SET B",
//        bsitSetB
//    });
//
//    // =====================================================
//    // BSIS
//    // =====================================================
//
//    model.addRow(new Object[] {
//        "BSIS",
//        "Institute of Computing",
//        "SET A",
//        bsisSetA
//    });
//
//    model.addRow(new Object[] {
//        "BSIS",
//        "Institute of Computing",
//        "SET B",
//        bsisSetB
//    });
//
//    // =====================================================
//    // ENTREPRENEURSHIP
//    // =====================================================
//
//    model.addRow(new Object[] {
//        "Entrepreneurship",
//        "Institute of Leadership",
//        "SET A",
//        entSetA
//    });
//
//    model.addRow(new Object[] {
//        "Entrepreneurship",
//        "Institute of Leadership",
//        "SET B",
//        entSetB
//    });
//
//    // =====================================================
//    // BSED MATHEMATICS
//    // =====================================================
//
//    model.addRow(new Object[] {
//        "BSED Mathematics",
//        "Institute of Advance Studies",
//        "SET A",
//        bsedMathSetA
//    });
//
//    model.addRow(new Object[] {
//        "BSED Mathematics",
//        "Institute of Advance Studies",
//        "SET B",
//        bsedMathSetB
//    });
//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pillarDesignPanel = new javax.swing.JPanel();
        lblADMIN = new javax.swing.JLabel();
        lblDASHBOARD = new javax.swing.JLabel();
        AdminLogo = new javax.swing.JLabel();
        mainAdminDashboard = new javax.swing.JPanel();
        upperDesignPanel = new javax.swing.JPanel();
        universityName = new javax.swing.JLabel();
        universityLogo = new javax.swing.JLabel();
        tabAdminDashboard = new javax.swing.JTabbedPane();
        panelStudent = new javax.swing.JPanel();
        lblSearchStudent = new javax.swing.JLabel();
        txtSearchStudent = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        scrollStudent = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        btnEditStudent = new javax.swing.JButton();
        btnDeleteStudents = new javax.swing.JButton();
        btnRefreshStudents = new javax.swing.JButton();
        panelProgram = new javax.swing.JPanel();
        scrollProgram = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        tblProgram = new javax.swing.JButton();
        panelProfessor = new javax.swing.JPanel();
        panelPaddingProgram = new javax.swing.JPanel();
        lblProgram = new javax.swing.JLabel();
        cmbProgram = new javax.swing.JComboBox<>();
        panelPaddingSet = new javax.swing.JPanel();
        lblSet = new javax.swing.JLabel();
        cmbSet = new javax.swing.JComboBox<>();
        panelPaddingProfessor = new javax.swing.JPanel();
        lblProfessor = new javax.swing.JLabel();
        cmbProfessor = new javax.swing.JComboBox<>();
        btnAssignProfessor = new javax.swing.JButton();
        scrollProfessor = new javax.swing.JScrollPane();
        tblProfessor = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pillarDesignPanel.setBackground(new java.awt.Color(0, 51, 102));

        lblADMIN.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        lblADMIN.setForeground(new java.awt.Color(255, 255, 255));
        lblADMIN.setText("ADMIN");

        lblDASHBOARD.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        lblDASHBOARD.setForeground(new java.awt.Color(255, 255, 255));
        lblDASHBOARD.setText("DASHBOARD");

        AdminLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image-removebg-preview (2)_1.png"))); // NOI18N

        javax.swing.GroupLayout pillarDesignPanelLayout = new javax.swing.GroupLayout(pillarDesignPanel);
        pillarDesignPanel.setLayout(pillarDesignPanelLayout);
        pillarDesignPanelLayout.setHorizontalGroup(
            pillarDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pillarDesignPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(pillarDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDASHBOARD)
                    .addGroup(pillarDesignPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblADMIN)))
                .addGap(8, 8, 8))
        );
        pillarDesignPanelLayout.setVerticalGroup(
            pillarDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pillarDesignPanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(AdminLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblADMIN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDASHBOARD)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        mainAdminDashboard.setBackground(new java.awt.Color(140, 174, 209));

        upperDesignPanel.setBackground(new java.awt.Color(0, 51, 102));

        universityName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        universityName.setForeground(new java.awt.Color(255, 255, 255));
        universityName.setText("ABBROPIA UNIVERSITY");

        universityLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/univ-removebg-preview (3).png"))); // NOI18N

        javax.swing.GroupLayout upperDesignPanelLayout = new javax.swing.GroupLayout(upperDesignPanel);
        upperDesignPanel.setLayout(upperDesignPanelLayout);
        upperDesignPanelLayout.setHorizontalGroup(
            upperDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperDesignPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(universityLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(universityName)
                .addContainerGap(373, Short.MAX_VALUE))
        );
        upperDesignPanelLayout.setVerticalGroup(
            upperDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperDesignPanelLayout.createSequentialGroup()
                .addGroup(upperDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(upperDesignPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(universityLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(upperDesignPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(universityName)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabAdminDashboard.setBackground(new java.awt.Color(0, 51, 102));
        tabAdminDashboard.setForeground(new java.awt.Color(255, 255, 255));
        tabAdminDashboard.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabAdminDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        panelStudent.setBackground(new java.awt.Color(255, 255, 255));
        panelStudent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblSearchStudent.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblSearchStudent.setForeground(new java.awt.Color(0, 51, 102));
        lblSearchStudent.setText("Search Student: ");

        txtSearchStudent.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        btnSearch.setBackground(new java.awt.Color(0, 51, 102));
        btnSearch.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        scrollStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        scrollStudent.setForeground(new java.awt.Color(0, 51, 102));
        scrollStudent.setToolTipText("");
        scrollStudent.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblStudents.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tblStudents.setForeground(new java.awt.Color(0, 51, 102));
        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Full Name", "Program", "Set", "Status"
            }
        ));
        scrollStudent.setViewportView(tblStudents);

        btnEditStudent.setBackground(new java.awt.Color(0, 51, 102));
        btnEditStudent.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnEditStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnEditStudent.setText("Edit Student");
        btnEditStudent.addActionListener(this::btnEditStudentActionPerformed);

        btnDeleteStudents.setBackground(new java.awt.Color(0, 51, 102));
        btnDeleteStudents.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnDeleteStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteStudents.setText("Delete Student");
        btnDeleteStudents.addActionListener(this::btnDeleteStudentsActionPerformed);

        btnRefreshStudents.setBackground(new java.awt.Color(0, 51, 102));
        btnRefreshStudents.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnRefreshStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnRefreshStudents.setText("Refresh");
        btnRefreshStudents.addActionListener(this::btnRefreshStudentsActionPerformed);

        javax.swing.GroupLayout panelStudentLayout = new javax.swing.GroupLayout(panelStudent);
        panelStudent.setLayout(panelStudentLayout);
        panelStudentLayout.setHorizontalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStudentLayout.createSequentialGroup()
                        .addComponent(lblSearchStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch))
                    .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelStudentLayout.createSequentialGroup()
                            .addComponent(btnEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnDeleteStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRefreshStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(scrollStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelStudentLayout.setVerticalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchStudent)
                    .addComponent(txtSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(scrollStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditStudent)
                    .addComponent(btnDeleteStudents)
                    .addComponent(btnRefreshStudents))
                .addGap(20, 20, 20))
        );

        tabAdminDashboard.addTab("Students", panelStudent);

        panelProgram.setBackground(new java.awt.Color(255, 255, 255));

        scrollProgram.setBackground(new java.awt.Color(0, 51, 102));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Program", "Institute", "Set", "Slot Remaining"
            }
        ));
        scrollProgram.setViewportView(jTable2);

        tblProgram.setBackground(new java.awt.Color(0, 51, 102));
        tblProgram.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tblProgram.setForeground(new java.awt.Color(255, 255, 255));
        tblProgram.setText("Refresh");

        javax.swing.GroupLayout panelProgramLayout = new javax.swing.GroupLayout(panelProgram);
        panelProgram.setLayout(panelProgramLayout);
        panelProgramLayout.setHorizontalGroup(
            panelProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProgramLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panelProgramLayout.setVerticalGroup(
            panelProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProgramLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(scrollProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tblProgram)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        tabAdminDashboard.addTab("Program", panelProgram);

        panelProfessor.setBackground(new java.awt.Color(255, 255, 255));

        panelPaddingProgram.setBackground(new java.awt.Color(0, 51, 102));

        lblProgram.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblProgram.setForeground(new java.awt.Color(255, 255, 255));
        lblProgram.setText("Program");

        cmbProgram.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cmbProgram.setForeground(new java.awt.Color(0, 51, 102));
        cmbProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT", "BSIS", "Entrepreneurship", "Public Administration", "BSED Mathematics", "BSED Eghlish", " " }));

        javax.swing.GroupLayout panelPaddingProgramLayout = new javax.swing.GroupLayout(panelPaddingProgram);
        panelPaddingProgram.setLayout(panelPaddingProgramLayout);
        panelPaddingProgramLayout.setHorizontalGroup(
            panelPaddingProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaddingProgramLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(cmbProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPaddingProgramLayout.setVerticalGroup(
            panelPaddingProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaddingProgramLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPaddingProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgram, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(cmbProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelPaddingSet.setBackground(new java.awt.Color(0, 51, 102));

        lblSet.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblSet.setForeground(new java.awt.Color(255, 255, 255));
        lblSet.setText("Set");

        cmbSet.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cmbSet.setForeground(new java.awt.Color(0, 51, 102));
        cmbSet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));

        javax.swing.GroupLayout panelPaddingSetLayout = new javax.swing.GroupLayout(panelPaddingSet);
        panelPaddingSet.setLayout(panelPaddingSetLayout);
        panelPaddingSetLayout.setHorizontalGroup(
            panelPaddingSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaddingSetLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblSet, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(cmbSet, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        panelPaddingSetLayout.setVerticalGroup(
            panelPaddingSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaddingSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblSet, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(cmbSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelPaddingProfessor.setBackground(new java.awt.Color(0, 51, 102));

        lblProfessor.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblProfessor.setForeground(new java.awt.Color(255, 255, 255));
        lblProfessor.setText("Professor");

        cmbProfessor.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cmbProfessor.setForeground(new java.awt.Color(0, 51, 102));
        cmbProfessor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prof. Santos", "Prof. Reyes", "Prof. Cruz", "Prof. Dela Peña" }));

        javax.swing.GroupLayout panelPaddingProfessorLayout = new javax.swing.GroupLayout(panelPaddingProfessor);
        panelPaddingProfessor.setLayout(panelPaddingProfessorLayout);
        panelPaddingProfessorLayout.setHorizontalGroup(
            panelPaddingProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaddingProfessorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(cmbProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        panelPaddingProfessorLayout.setVerticalGroup(
            panelPaddingProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPaddingProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(cmbProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnAssignProfessor.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnAssignProfessor.setForeground(new java.awt.Color(0, 51, 102));
        btnAssignProfessor.setText("ASSIGN PROFESSOR");

        tblProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Program", "Set", "Assign Prof"
            }
        ));
        scrollProfessor.setViewportView(tblProfessor);

        javax.swing.GroupLayout panelProfessorLayout = new javax.swing.GroupLayout(panelProfessor);
        panelProfessor.setLayout(panelProfessorLayout);
        panelProfessorLayout.setHorizontalGroup(
            panelProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfessorLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addGroup(panelProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAssignProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelPaddingProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelPaddingSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelPaddingProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panelProfessorLayout.setVerticalGroup(
            panelProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfessorLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(panelPaddingProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPaddingSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPaddingProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAssignProfessor)
                .addGap(18, 18, 18)
                .addComponent(scrollProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        tabAdminDashboard.addTab("Professor", panelProfessor);

        btnLogout.setBackground(new java.awt.Color(0, 51, 102));
        btnLogout.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout mainAdminDashboardLayout = new javax.swing.GroupLayout(mainAdminDashboard);
        mainAdminDashboard.setLayout(mainAdminDashboardLayout);
        mainAdminDashboardLayout.setHorizontalGroup(
            mainAdminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainAdminDashboardLayout.createSequentialGroup()
                .addGroup(mainAdminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainAdminDashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(upperDesignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainAdminDashboardLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(tabAdminDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainAdminDashboardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        mainAdminDashboardLayout.setVerticalGroup(
            mainAdminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainAdminDashboardLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(upperDesignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(tabAdminDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(pillarDesignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainAdminDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pillarDesignPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainAdminDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshStudentsActionPerformed
       loadStudentData();
        JOptionPane.showMessageDialog(
            this,
            "Student table refreshed!"
    );
    }//GEN-LAST:event_btnRefreshStudentsActionPerformed

    private void btnDeleteStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentsActionPerformed
        int selectedRow =
            tblStudents.getSelectedRow();

    // CHECK SELECTION
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a student!");
        return;
    }

    // CONFIRM DELETE
    int choice = JOptionPane.showConfirmDialog(this,"Are you sure you want to delete this student?","Delete Student",JOptionPane.YES_NO_OPTION);

    // DELETE
    if (choice == JOptionPane.YES_OPTION) {
        studentModel.removeRow(selectedRow);

        JOptionPane.showMessageDialog( this, "Student deleted successfully!");
    }
    }//GEN-LAST:event_btnDeleteStudentsActionPerformed

    private void btnEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStudentActionPerformed
         int selectedRow = tblStudents.getSelectedRow();

    // CHECK IF ROW SELECTED
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog( this, "Please select a student!");
        return;
    }

    // STATUS OPTIONS
    String[] statusOptions = {
        "ENROLLED",
        "NOT ENROLLED",
        "PENDING"
    };

    // SELECT STATUS
    String newStatus =
            (String) JOptionPane.showInputDialog(
                    this,
                    "Select Enrollment Status:",
                    "Edit Status",
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    statusOptions,
                    statusOptions[0]
            );

    // IF NOT CANCELLED
    if (newStatus != null) {

        tblStudents.setValueAt(
                newStatus,
                selectedRow,
                4
        );

        JOptionPane.showMessageDialog(
                this,
                "Student status updated!"
        );
    }
    }//GEN-LAST:event_btnEditStudentActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
         String search =
            txtSearchStudent.getText().trim().toLowerCase();

    DefaultTableModel model =
            (DefaultTableModel) tblStudents.getModel();

    // LOOP TABLE
    for (int i = 0; i < model.getRowCount(); i++) {
        String studentID =model.getValueAt(i, 0).toString().toLowerCase();
        String fullName = model.getValueAt(i, 1).toString().toLowerCase();

        // CHECK MATCH
        if (studentID.contains(search) || fullName.contains(search)) {
            tblStudents.setRowSelectionInterval(i, i);
            return;
        }
    }

    JOptionPane.showMessageDialog(this,"Student not found!");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Logout Confirmation",
            JOptionPane.YES_NO_OPTION
    );

    // IF YES
    if (choice == JOptionPane.YES_OPTION) {

        WelcomeFrame welcome =
                new WelcomeFrame();

        welcome.setVisible(true);

        dispose();
    }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminLogo;
    private javax.swing.JButton btnAssignProfessor;
    private javax.swing.JButton btnDeleteStudents;
    private javax.swing.JButton btnEditStudent;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefreshStudents;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbProfessor;
    private javax.swing.JComboBox<String> cmbProgram;
    private javax.swing.JComboBox<String> cmbSet;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblADMIN;
    private javax.swing.JLabel lblDASHBOARD;
    private javax.swing.JLabel lblProfessor;
    private javax.swing.JLabel lblProgram;
    private javax.swing.JLabel lblSearchStudent;
    private javax.swing.JLabel lblSet;
    private javax.swing.JPanel mainAdminDashboard;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelPaddingProfessor;
    private javax.swing.JPanel panelPaddingProgram;
    private javax.swing.JPanel panelPaddingSet;
    private javax.swing.JPanel panelProfessor;
    private javax.swing.JPanel panelProgram;
    private javax.swing.JPanel panelStudent;
    private javax.swing.JPanel pillarDesignPanel;
    private javax.swing.JScrollPane scrollProfessor;
    private javax.swing.JScrollPane scrollProgram;
    private javax.swing.JScrollPane scrollStudent;
    private javax.swing.JTabbedPane tabAdminDashboard;
    private javax.swing.JTable tblProfessor;
    private javax.swing.JButton tblProgram;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtSearchStudent;
    private javax.swing.JLabel universityLogo;
    private javax.swing.JLabel universityName;
    private javax.swing.JPanel upperDesignPanel;
    // End of variables declaration//GEN-END:variables
}
