/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enrollmentsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Rochelle D. Abella
 */
public class CreateAccountFrame  extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateAccountFrame .class.getName());

    /**
     * Creates new form LoginFrame
     */
    public CreateAccountFrame () {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLeft = new javax.swing.JPanel();
        panelRight = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblConfirmPassword = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        remiderPanel = new javax.swing.JPanel();
        lblSixChar = new javax.swing.JLabel();
        lblCapitalNumbers = new javax.swing.JLabel();
        lblMustConfirmPassword = new javax.swing.JLabel();
        pillardesignPanel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnCreateAccount = new javax.swing.JButton();
        lblAlreadyHaveAnAccount = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        chkShowPassword = new javax.swing.JCheckBox();
        lblCreate = new javax.swing.JLabel();
        lblYourAccount = new javax.swing.JLabel();
        lblFillInformation = new javax.swing.JLabel();
        lblYouraccount = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLeft.setBackground(new java.awt.Color(0, 51, 102));

        panelRight.setBackground(new java.awt.Color(255, 255, 255));

        lblUsername.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 51, 102));
        lblUsername.setText("Username");

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(0, 51, 102));
        txtUsername.setText("Enter Username");
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameMouseClicked(evt);
            }
        });
        txtUsername.addActionListener(this::txtUsernameActionPerformed);

        lblPassword.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 51, 102));
        lblPassword.setText("Password");

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 51, 102));
        txtPassword.addActionListener(this::txtPasswordActionPerformed);

        lblConfirmPassword.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblConfirmPassword.setForeground(new java.awt.Color(0, 51, 102));
        lblConfirmPassword.setText("Confirm Password");

        txtConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtConfirmPassword.setForeground(new java.awt.Color(0, 51, 102));
        txtConfirmPassword.addActionListener(this::txtConfirmPasswordActionPerformed);

        remiderPanel.setBackground(new java.awt.Color(160, 175, 189));

        lblSixChar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblSixChar.setForeground(new java.awt.Color(0, 51, 102));
        lblSixChar.setText("✔ Be at least 6 characters");

        lblCapitalNumbers.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblCapitalNumbers.setForeground(new java.awt.Color(0, 51, 102));
        lblCapitalNumbers.setText("✔ Contain letters and numbers");

        lblMustConfirmPassword.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblMustConfirmPassword.setForeground(new java.awt.Color(0, 51, 102));
        lblMustConfirmPassword.setText("✔ Must confirm password");

        javax.swing.GroupLayout remiderPanelLayout = new javax.swing.GroupLayout(remiderPanel);
        remiderPanel.setLayout(remiderPanelLayout);
        remiderPanelLayout.setHorizontalGroup(
            remiderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remiderPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(remiderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCapitalNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(remiderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblMustConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSixChar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        remiderPanelLayout.setVerticalGroup(
            remiderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remiderPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblSixChar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCapitalNumbers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMustConfirmPassword)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pillardesignPanelLayout = new javax.swing.GroupLayout(pillardesignPanel);
        pillardesignPanel.setLayout(pillardesignPanelLayout);
        pillardesignPanelLayout.setHorizontalGroup(
            pillardesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pillardesignPanelLayout.setVerticalGroup(
            pillardesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        btnCancel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 51, 102));
        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        btnCreateAccount.setBackground(new java.awt.Color(0, 51, 102));
        btnCreateAccount.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateAccount.setText("CREATE ACCOUNT");
        btnCreateAccount.addActionListener(this::btnCreateAccountActionPerformed);

        lblAlreadyHaveAnAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAlreadyHaveAnAccount.setForeground(new java.awt.Color(0, 51, 102));
        lblAlreadyHaveAnAccount.setText("Already have an account? ");

        btnLogin.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 51, 102));
        btnLogin.setText("Login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        chkShowPassword.setForeground(new java.awt.Color(0, 51, 102));
        chkShowPassword.setText("Show Password");
        chkShowPassword.addActionListener(this::chkShowPasswordActionPerformed);

        javax.swing.GroupLayout panelRightLayout = new javax.swing.GroupLayout(panelRight);
        panelRight.setLayout(panelRightLayout);
        panelRightLayout.setHorizontalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRightLayout.createSequentialGroup()
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword)
                            .addComponent(txtConfirmPassword)
                            .addComponent(lblConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRightLayout.createSequentialGroup()
                                .addComponent(pillardesignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(remiderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelRightLayout.createSequentialGroup()
                                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))))
                            .addComponent(chkShowPassword, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblAlreadyHaveAnAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panelRightLayout.setVerticalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRightLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblConfirmPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(chkShowPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(remiderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pillardesignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlreadyHaveAnAccount)
                    .addComponent(btnLogin))
                .addGap(31, 31, 31))
        );

        lblCreate.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblCreate.setForeground(new java.awt.Color(255, 255, 255));
        lblCreate.setText("CREATE");

        lblYourAccount.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblYourAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblYourAccount.setText("YOUR ACCOUNT");

        lblFillInformation.setForeground(new java.awt.Color(255, 255, 255));
        lblFillInformation.setText("FILL INFORMATION TO CREATE");

        lblYouraccount.setForeground(new java.awt.Color(255, 255, 255));
        lblYouraccount.setText("YOUR ACCOUNT");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/univlogo.png"))); // NOI18N

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLeftLayout.createSequentialGroup()
                        .addComponent(lblCreate)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLeftLayout.createSequentialGroup()
                        .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLeftLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFillInformation)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLeftLayout.createSequentialGroup()
                                        .addComponent(lblYouraccount)
                                        .addGap(36, 36, 36))))
                            .addComponent(lblYourAccount)
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addComponent(panelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLeftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblYourAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFillInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblYouraccount, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed

    // GET INPUTS
    String username = txtUsername.getText().trim();
    String password = txtPassword.getText().trim();
    String confirmPassword = txtConfirmPassword.getText().trim();

    // ======================================================
    // CHECK EMPTY USERNAME
    // ======================================================

    if (username.isEmpty()) {

        JOptionPane.showMessageDialog( this,"Username is required!");
        txtUsername.requestFocus();
        return;
    }
    
    // ======================================================
    // CHECK EMPTY PASSWORD
    // ======================================================
    if (password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Password is required!");
        txtPassword.requestFocus();
        return;
    }

    // ======================================================
    // CHECK EMPTY CONFIRM PASSWORD
    // ======================================================

    if (confirmPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this,"Please confirm your password!");
        txtConfirmPassword.requestFocus();
        return;
    }

    // ======================================================
    // USERNAME SHOULD NOT CONTAIN SPACES
    // ======================================================

    if (username.contains(" ")) {
        JOptionPane.showMessageDialog(this, "Username should not contain spaces!");
        txtUsername.requestFocus();
        return;
    }

    // ======================================================
    // PASSWORD MINIMUM LENGTH
    // ======================================================

    if (password.length() < 6) {
        JOptionPane.showMessageDialog( this,"Password must be at least 6 characters!");
        txtPassword.requestFocus();
        return;
    }

    // ======================================================
    // PASSWORD MUST CONTAIN LETTERS AND NUMBERS
    // ======================================================

    boolean hasLetter = false;
    boolean hasNumber = false;

    for (char c : password.toCharArray()) {
        if (Character.isLetter(c)) {
            hasLetter = true;
        }

        if (Character.isDigit(c)) {
            hasNumber = true;
        }
    }

    if (!hasLetter || !hasNumber) {
        JOptionPane.showMessageDialog(this,"Password must contain letters and numbers!");
        txtPassword.requestFocus();
        return;
    }

    // ======================================================
    // CHECK PASSWORD MATCH
    // ======================================================

    if (!password.equals(confirmPassword)) {
        JOptionPane.showMessageDialog(this,"Password does not match!");
        txtConfirmPassword.requestFocus();
        return;
    }

    // ======================================================
    // SAVE ACCOUNT
    // ======================================================

    DataStore.savedUsername = username;
    DataStore.savedPassword = password;

    // ======================================================
    // SUCCESS MESSAGE
    // ======================================================

    JOptionPane.showMessageDialog(
            this,
            "Account Created Successfully!"
    );

    // =====================================================
// OPEN ENROLLMENT FRAME
// =====================================================

StudentEnrollmentFrame enrollment =
        new StudentEnrollmentFrame();

enrollment.setVisible(true);

dispose();
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        new LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        txtUsername.setText("Enter Username");
        txtPassword.setText("");
        txtConfirmPassword.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handlin javax.swing. code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPasswordActionPerformed

    private void txtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseClicked
        if (txtUsername.isEnabled())
        {
            txtUsername.setText("");
        }
    }//GEN-LAST:event_txtUsernameMouseClicked

    private void chkShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPasswordActionPerformed
        if (chkShowPassword.isSelected()) {
            txtPassword.setEchoChar((char) 0);
            txtConfirmPassword.setEchoChar((char) 0);
        } else {
            txtPassword.setEchoChar('*');
            txtConfirmPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chkShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreateAccountFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chkShowPassword;
    private javax.swing.JLabel lblAlreadyHaveAnAccount;
    private javax.swing.JLabel lblCapitalNumbers;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblFillInformation;
    private javax.swing.JLabel lblMustConfirmPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSixChar;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblYourAccount;
    private javax.swing.JLabel lblYouraccount;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel pillardesignPanel;
    private javax.swing.JPanel remiderPanel;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
