/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enrollmentsystem;

import javax.swing.JOptionPane;


/**
 *
 * @author Rochelle D. Abella
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgUserType = new javax.swing.ButtonGroup();
        panelLeft = new javax.swing.JPanel();
        panelRight = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblUserType = new javax.swing.JLabel();
        rbtnStudent = new javax.swing.JRadioButton();
        rbtnAdmin = new javax.swing.JRadioButton();
        lblAlreadyHaveAnAccount = new javax.swing.JLabel();
        btnCreateAccount = new javax.swing.JButton();
        chkShowPassword = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLeft.setBackground(new java.awt.Color(0, 51, 102));

        panelRight.setBackground(new java.awt.Color(255, 255, 255));

        lblUsername.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 51, 102));
        lblUsername.setText("Username");

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(0, 51, 102));
        txtUsername.setText("Enter Username");
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameMouseClicked(evt);
            }
        });
        txtUsername.addActionListener(this::txtUsernameActionPerformed);

        lblPassword.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 51, 102));
        lblPassword.setText("Password");

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 51, 102));
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        txtPassword.addActionListener(this::txtPasswordActionPerformed);

        btnLogin.setBackground(new java.awt.Color(0, 51, 102));
        btnLogin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOG IN");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        lblUserType.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblUserType.setForeground(new java.awt.Color(0, 51, 102));
        lblUserType.setText("Login as:");

        rbtnStudent.setBackground(new java.awt.Color(255, 255, 255));
        bgUserType.add(rbtnStudent);
        rbtnStudent.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        rbtnStudent.setForeground(new java.awt.Color(0, 51, 102));
        rbtnStudent.setText("Student");
        rbtnStudent.addActionListener(this::rbtnStudentActionPerformed);

        rbtnAdmin.setBackground(new java.awt.Color(255, 255, 255));
        bgUserType.add(rbtnAdmin);
        rbtnAdmin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        rbtnAdmin.setForeground(new java.awt.Color(0, 51, 102));
        rbtnAdmin.setText("Admin");

        lblAlreadyHaveAnAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAlreadyHaveAnAccount.setForeground(new java.awt.Color(0, 51, 102));
        lblAlreadyHaveAnAccount.setText("Already have an account? ");

        btnCreateAccount.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCreateAccount.setForeground(new java.awt.Color(0, 51, 102));
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(this::btnCreateAccountActionPerformed);

        chkShowPassword.setForeground(new java.awt.Color(0, 51, 102));
        chkShowPassword.setText("Show Password");
        chkShowPassword.addActionListener(this::chkShowPasswordActionPerformed);

        javax.swing.GroupLayout panelRightLayout = new javax.swing.GroupLayout(panelRight);
        panelRight.setLayout(panelRightLayout);
        panelRightLayout.setHorizontalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRightLayout.createSequentialGroup()
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelRightLayout.createSequentialGroup()
                                .addComponent(lblUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkShowPassword))
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword)
                            .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(rbtnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblAlreadyHaveAnAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateAccount)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panelRightLayout.setVerticalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRightLayout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblUserType))
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(chkShowPassword)))
                .addGap(18, 18, 18)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnStudent)
                    .addComponent(rbtnAdmin))
                .addGap(129, 129, 129)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlreadyHaveAnAccount)
                    .addComponent(btnCreateAccount))
                .addGap(32, 32, 32))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Welcome back!");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("LOGIN TO YOUR ACCOUNT");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TO CONTINUE");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/univlogo.png"))); // NOI18N

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel8))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30)
                .addComponent(panelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLeftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handlin javax.swing. code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    // GET INPUTS
    String username = txtUsername.getText().trim();
    String password = txtPassword.getText().trim();

    // ======================================================
    // CHECK IF USER TYPE IS SELECTED
    // ======================================================

    if (!rbtnStudent.isSelected() && !rbtnAdmin.isSelected()) {

        JOptionPane.showMessageDialog(this, "Please select login type!");
        return;
    }

    if (username.isEmpty()) {
        JOptionPane.showMessageDialog(this,"Username is required!");
        txtUsername.requestFocus();
        return;
    }

    if (password.isEmpty()) {
        JOptionPane.showMessageDialog(this,"Password is required!");
        txtPassword.requestFocus();
        return;
    }

    if (username.contains(" ")) {
        JOptionPane.showMessageDialog(this,"Username should not contain spaces!");
        txtUsername.requestFocus();
        return;
    }

    // ======================================================
    // STUDENT LOGIN
    // ======================================================

    if (rbtnStudent.isSelected()) {
        // CHECK IF USERNAME EXISTS
        if (!username.equals(DataStore.savedUsername)) {
            JOptionPane.showMessageDialog(this,"Student username does not exist!");
            return;
        }

        // CHECK PASSWORD
        if (!password.equals(DataStore.savedPassword)) {
            JOptionPane.showMessageDialog(this,"Incorrect student password!");
            return;
        }

        // SUCCESS LOGIN
        JOptionPane.showMessageDialog(this,"Student Login Successful!");

 // =====================================================
// OPEN STUDENT DASHBOARD
// =====================================================

        StudentDashboardFrame dashboard = new StudentDashboardFrame();
        dashboard.setVisible(true);
        dispose();
    }

    // ======================================================
    // ADMIN LOGIN
    // ======================================================

    else if (rbtnAdmin.isSelected()) {
        // FIXED ADMIN ACCOUNT
        String adminUsername = "admin";
        String adminPassword = "admin123";

        // CHECK USERNAME
        if (!username.equals(adminUsername)) {
            JOptionPane.showMessageDialog(this, "Admin username is incorrect!");
            return;
        }

        // CHECK PASSWORD
        if (!password.equals(adminPassword)) {

            JOptionPane.showMessageDialog(this, "Admin password is incorrect!");
            return;
        }

        // SUCCESS LOGIN
        JOptionPane.showMessageDialog( this, "Admin Login Successful!");

        // OPEN ADMIN DASHBOARD
        AdminDashboardFrame admin = new AdminDashboardFrame();
        admin.setVisible(true);

        // CLOSE LOGIN FRAME
        dispose();
    }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
    CreateAccountFrame create = new CreateAccountFrame();
    create.setVisible(true);
    dispose();
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void txtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseClicked
        if (txtUsername.isEnabled())
        {
            txtUsername.setText("");
        }
    }//GEN-LAST:event_txtUsernameMouseClicked

    private void rbtnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnStudentActionPerformed

    private void chkShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPasswordActionPerformed
        
    if (chkShowPassword.isSelected()) {
        // SHOW PASSWORD
        txtPassword.setEchoChar((char) 0);

    } else {
        // HIDE PASSWORD
        txtPassword.setEchoChar('*');
    }

    }//GEN-LAST:event_chkShowPasswordActionPerformed

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgUserType;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chkShowPassword;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAlreadyHaveAnAccount;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    private javax.swing.JRadioButton rbtnAdmin;
    private javax.swing.JRadioButton rbtnStudent;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
