/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enrollmentsystem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Rochelle D. Abella
 */
public class StudentDashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentDashboardFrame.class.getName());

    /**
     * Creates new form StudentDashboardFrame
     */
    public StudentDashboardFrame() {
        initComponents();
        displayStudentInformation();
        displayEnrolledSubjects();
        setFieldsReadOnly();
        
    }
// DISPLAY STUDENT INFORMATION

private void displayStudentInformation() {

    // AUTO GENERATED STUDENT ID
    String studentID =
            "2026-" + (int)(Math.random() * 9000 + 1000);

    // AUTO STATUS
    String status = "PENDING";

    // AUTO SET
    String set = "SET A";

    // =====================================================
    // AUTO INSTITUTE
    // =====================================================

    String institute = "";

    if (DataStore.firstChoice.equals("BSIT")  || DataStore.firstChoice.equals("BSIS")) {
        institute = "Institute of Computing";
    }

    else if (DataStore.firstChoice.equals( "Entrepreneurship") || DataStore.firstChoice.equals("Public Administration")) {
        institute = "Institute of Leadership";
    }

    else if (DataStore.firstChoice.equals( "BSED Mathematics") || DataStore.firstChoice.equals(  "BSED English")) {
        institute = "Institute of Advance Studies";
    }

    // DISPLAY DATA
    txtSchoolID.setText(studentID);
    txtFullName.setText(DataStore.fullName);
    txtProgram.setText(DataStore.firstChoice);
    txtInstitute.setText(institute);
    txtSet.setText(set);
    txtStatus.setText(status);
    txtAcademicYear.setText("2026 - 2027");
    txtSemester.setText("1st Semester");
    txtSchedule.setText("MONDAY - FRIDAY");
}

private void displayEnrolledSubjects() {

    DefaultTableModel model = (DefaultTableModel) tblEnrolledSubjects.getModel();
    // CLEAR TABLE
    model.setRowCount(0);


    // BSIT SUBJECTS
    if (DataStore.firstChoice.equals("BSIT")) {
        model.addRow(new Object[] {
            "IT101",
            "Introduction to Computing",
            "3",
            "Prof. Santos",
            "MWF 7-9 AM"
        });

        model.addRow(new Object[] {
            "IT102",
            "Programming 1",
            "3",
            "Prof. Reyes",
            "TTH 10-12 PM"
        });

        model.addRow(new Object[] {
            "IT103",
            "Database Management",
            "3",
            "Prof. Cruz",
            "MWF 1-3 PM"
        });
    }

    // BSIS SUBJECTS
    else if (DataStore.firstChoice.equals("BSIS")) {

        model.addRow(new Object[] {
            "IS101",
            "Information Systems",
            "3",
            "Prof. Garcia",
            "MWF 9-11 AM"
        });

        model.addRow(new Object[] {
            "IS102",
            "Business Analytics",
            "3",
            "Prof. Ramos",
            "TTH 1-3 PM"
        });
    }

    // ENTREPRENEURSHIP
    else if (DataStore.firstChoice.equals(
            "Entrepreneurship")) {

        model.addRow(new Object[] {
            "ENT101",
            "Entrepreneurial Mindset",
            "3",
            "Prof. Flores",
            "MWF 8-10 AM"
        });
    }
}

private void setFieldsReadOnly() {
    txtSchoolID.setEditable(false);
    txtFullName.setEditable(false);
    txtProgram.setEditable(false);
    txtInstitute.setEditable(false);
    txtSet.setEditable(false);
    txtSchedule.setEditable(false);
    txtAcademicYear.setEditable(false);
    txtSemester.setEditable(false);
    txtStatus.setEditable(false);    
    txtSchoolID.setFocusable(false);
    txtFullName.setFocusable(false);

    txtProgram.setFocusable(false);
    txtInstitute.setFocusable(false);
    txtSet.setFocusable(false);
    txtSchedule.setFocusable(false);
    txtAcademicYear.setFocusable(false);
    txtSemester.setFocusable(false);
    txtStatus.setFocusable(false);
}
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        upperPillarDesign = new javax.swing.JPanel();
        universityName = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        studentInfo = new javax.swing.JPanel();
        upperStudentInfo = new javax.swing.JPanel();
        lblStudentInfo = new javax.swing.JLabel();
        lblSchoolID = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblProgram = new javax.swing.JLabel();
        lblInstitute = new javax.swing.JLabel();
        lblSet = new javax.swing.JLabel();
        lblSchedule = new javax.swing.JLabel();
        lblAcademicYear = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtSchoolID = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        txtProgram = new javax.swing.JTextField();
        txtInstitute = new javax.swing.JTextField();
        txtSet = new javax.swing.JTextField();
        txtSchedule = new javax.swing.JTextField();
        txtAcademicYear = new javax.swing.JTextField();
        txtSemester = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        enrolledSubject = new javax.swing.JPanel();
        upperEnrolledSubjects = new javax.swing.JPanel();
        lblEnrolledSubject = new javax.swing.JLabel();
        scrollSubjects = new javax.swing.JScrollPane();
        tblEnrolledSubjects = new javax.swing.JTable();
        pillarDesignPanel = new javax.swing.JPanel();
        lblSTUDENT = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        logoStudentDashboard = new javax.swing.JLabel();
        btnEditProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        upperPillarDesign.setBackground(new java.awt.Color(0, 51, 102));

        universityName.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        universityName.setForeground(new java.awt.Color(255, 255, 255));
        universityName.setText("ABBAROPIA UNIVERSITY");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/univ-removebg-preview (3).png"))); // NOI18N

        javax.swing.GroupLayout upperPillarDesignLayout = new javax.swing.GroupLayout(upperPillarDesign);
        upperPillarDesign.setLayout(upperPillarDesignLayout);
        upperPillarDesignLayout.setHorizontalGroup(
            upperPillarDesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPillarDesignLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(universityName)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        upperPillarDesignLayout.setVerticalGroup(
            upperPillarDesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPillarDesignLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(universityName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(upperPillarDesignLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentInfo.setBackground(new java.awt.Color(255, 255, 255));
        studentInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 51, 102)));

        upperStudentInfo.setBackground(new java.awt.Color(0, 51, 102));

        lblStudentInfo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblStudentInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentInfo.setText("STUDENT INFORMATION");

        javax.swing.GroupLayout upperStudentInfoLayout = new javax.swing.GroupLayout(upperStudentInfo);
        upperStudentInfo.setLayout(upperStudentInfoLayout);
        upperStudentInfoLayout.setHorizontalGroup(
            upperStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperStudentInfoLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lblStudentInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        upperStudentInfoLayout.setVerticalGroup(
            upperStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperStudentInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStudentInfo)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        lblSchoolID.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblSchoolID.setForeground(new java.awt.Color(0, 51, 102));
        lblSchoolID.setText("SCHOOL ID");

        lblFullName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(0, 51, 102));
        lblFullName.setText("FULL NAME");

        lblProgram.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblProgram.setForeground(new java.awt.Color(0, 51, 102));
        lblProgram.setText("PROGRAM");

        lblInstitute.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblInstitute.setForeground(new java.awt.Color(0, 51, 102));
        lblInstitute.setText("INSTITUTE");

        lblSet.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblSet.setForeground(new java.awt.Color(0, 51, 102));
        lblSet.setText("SET");

        lblSchedule.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblSchedule.setForeground(new java.awt.Color(0, 51, 102));
        lblSchedule.setText("SCHEDULE");

        lblAcademicYear.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblAcademicYear.setForeground(new java.awt.Color(0, 51, 102));
        lblAcademicYear.setText("ACADEMIC YEAR");

        lblSemester.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblSemester.setForeground(new java.awt.Color(0, 51, 102));
        lblSemester.setText("SEMESTER");

        lblStatus.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(0, 51, 102));
        lblStatus.setText("STATUS");

        txtSchoolID.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtSchoolID.setForeground(new java.awt.Color(0, 51, 102));
        txtSchoolID.addActionListener(this::txtSchoolIDActionPerformed);

        txtFullName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtFullName.setForeground(new java.awt.Color(0, 51, 102));
        txtFullName.addActionListener(this::txtFullNameActionPerformed);

        txtProgram.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtProgram.setForeground(new java.awt.Color(0, 51, 102));
        txtProgram.addActionListener(this::txtProgramActionPerformed);

        txtInstitute.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtInstitute.setForeground(new java.awt.Color(0, 51, 102));
        txtInstitute.addActionListener(this::txtInstituteActionPerformed);

        txtSet.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtSet.setForeground(new java.awt.Color(0, 51, 102));
        txtSet.addActionListener(this::txtSetActionPerformed);

        txtSchedule.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtSchedule.setForeground(new java.awt.Color(0, 51, 102));
        txtSchedule.addActionListener(this::txtScheduleActionPerformed);

        txtAcademicYear.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtAcademicYear.setForeground(new java.awt.Color(0, 51, 102));
        txtAcademicYear.addActionListener(this::txtAcademicYearActionPerformed);

        txtSemester.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtSemester.setForeground(new java.awt.Color(0, 51, 102));
        txtSemester.addActionListener(this::txtSemesterActionPerformed);

        txtStatus.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtStatus.setForeground(new java.awt.Color(0, 51, 102));
        txtStatus.addActionListener(this::txtStatusActionPerformed);

        javax.swing.GroupLayout studentInfoLayout = new javax.swing.GroupLayout(studentInfo);
        studentInfo.setLayout(studentInfoLayout);
        studentInfoLayout.setHorizontalGroup(
            studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(upperStudentInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(studentInfoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSet, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblInstitute, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSchoolID, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAcademicYear)
                    .addComponent(lblSemester)
                    .addComponent(lblStatus))
                .addGap(56, 56, 56)
                .addGroup(studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAcademicYear, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSchoolID, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInstitute, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSet, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        studentInfoLayout.setVerticalGroup(
            studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentInfoLayout.createSequentialGroup()
                .addComponent(upperStudentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSchoolID)
                    .addComponent(txtSchoolID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstitute, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInstitute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSet, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcademicYear, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAcademicYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        enrolledSubject.setBackground(new java.awt.Color(255, 255, 255));
        enrolledSubject.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 51, 102)));

        upperEnrolledSubjects.setBackground(new java.awt.Color(0, 51, 102));

        lblEnrolledSubject.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblEnrolledSubject.setForeground(new java.awt.Color(255, 255, 255));
        lblEnrolledSubject.setText("ENROLLED SUBJECTS");

        javax.swing.GroupLayout upperEnrolledSubjectsLayout = new javax.swing.GroupLayout(upperEnrolledSubjects);
        upperEnrolledSubjects.setLayout(upperEnrolledSubjectsLayout);
        upperEnrolledSubjectsLayout.setHorizontalGroup(
            upperEnrolledSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperEnrolledSubjectsLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(lblEnrolledSubject)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        upperEnrolledSubjectsLayout.setVerticalGroup(
            upperEnrolledSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperEnrolledSubjectsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEnrolledSubject)
                .addContainerGap())
        );

        tblEnrolledSubjects.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tblEnrolledSubjects.setForeground(new java.awt.Color(0, 51, 102));
        tblEnrolledSubjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODE", "SUBJECT", "UNITS", "PROF", "SCHED"
            }
        ));
        scrollSubjects.setViewportView(tblEnrolledSubjects);

        javax.swing.GroupLayout enrolledSubjectLayout = new javax.swing.GroupLayout(enrolledSubject);
        enrolledSubject.setLayout(enrolledSubjectLayout);
        enrolledSubjectLayout.setHorizontalGroup(
            enrolledSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(upperEnrolledSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(enrolledSubjectLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(scrollSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        enrolledSubjectLayout.setVerticalGroup(
            enrolledSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enrolledSubjectLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(upperEnrolledSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        pillarDesignPanel.setBackground(new java.awt.Color(0, 51, 102));

        lblSTUDENT.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        lblSTUDENT.setForeground(new java.awt.Color(255, 255, 255));
        lblSTUDENT.setText("STUDENT ");

        lblDashboard.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setText("DASHBOARD");

        logoStudentDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Download_Illustration_of_books__graduation_cap_and_medal_for_free-removebg-preview (1).png"))); // NOI18N

        javax.swing.GroupLayout pillarDesignPanelLayout = new javax.swing.GroupLayout(pillarDesignPanel);
        pillarDesignPanel.setLayout(pillarDesignPanelLayout);
        pillarDesignPanelLayout.setHorizontalGroup(
            pillarDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pillarDesignPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pillarDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDashboard)
                    .addComponent(logoStudentDashboard)
                    .addGroup(pillarDesignPanelLayout.createSequentialGroup()
                        .addComponent(lblSTUDENT)
                        .addGap(18, 18, 18)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pillarDesignPanelLayout.setVerticalGroup(
            pillarDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pillarDesignPanelLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(logoStudentDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSTUDENT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEditProfile.setBackground(new java.awt.Color(0, 51, 102));
        btnEditProfile.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnEditProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnEditProfile.setText("EDIT PROFILE");
        btnEditProfile.addActionListener(this::btnEditProfileActionPerformed);

        btnLogout.setBackground(new java.awt.Color(0, 51, 102));
        btnLogout.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(pillarDesignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(btnEditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(enrolledSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(studentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(upperPillarDesign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(upperPillarDesign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(enrolledSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditProfile)
                    .addComponent(btnLogout))
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(pillarDesignPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSchoolIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSchoolIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSchoolIDActionPerformed

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameActionPerformed

    private void txtProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProgramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProgramActionPerformed

    private void txtInstituteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstituteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstituteActionPerformed

    private void txtSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetActionPerformed

    private void txtScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScheduleActionPerformed

    private void txtAcademicYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcademicYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcademicYearActionPerformed

    private void txtSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemesterActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void btnEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProfileActionPerformed
        StudentEnrollmentFrame enrollment = new StudentEnrollmentFrame();
        enrollment.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEditProfileActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
            int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Logout Confirmation",
            JOptionPane.YES_NO_OPTION
    );

    // IF YES
    if (choice == JOptionPane.YES_OPTION) {

        WelcomeFrame welcome =
                new WelcomeFrame();

        welcome.setVisible(true);

        dispose();
    }

    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentDashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditProfile;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel enrolledSubject;
    private javax.swing.JLabel lblAcademicYear;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblEnrolledSubject;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblInstitute;
    private javax.swing.JLabel lblProgram;
    private javax.swing.JLabel lblSTUDENT;
    private javax.swing.JLabel lblSchedule;
    private javax.swing.JLabel lblSchoolID;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblSet;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStudentInfo;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoStudentDashboard;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pillarDesignPanel;
    private javax.swing.JScrollPane scrollSubjects;
    private javax.swing.JPanel studentInfo;
    private javax.swing.JTable tblEnrolledSubjects;
    private javax.swing.JTextField txtAcademicYear;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtInstitute;
    private javax.swing.JTextField txtProgram;
    private javax.swing.JTextField txtSchedule;
    private javax.swing.JTextField txtSchoolID;
    private javax.swing.JTextField txtSemester;
    private javax.swing.JTextField txtSet;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JLabel universityName;
    private javax.swing.JPanel upperEnrolledSubjects;
    private javax.swing.JPanel upperPillarDesign;
    private javax.swing.JPanel upperStudentInfo;
    // End of variables declaration//GEN-END:variables
}
