/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enrollmentsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Rochelle D. Abella
 */
public class StudentEnrollmentFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentEnrollmentFrame.class.getName());

    /**
     * Creates new form StudentEnrollmentFrame
     */
    public StudentEnrollmentFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        tabEnrollment = new javax.swing.JTabbedPane();
        panelPersonalInfo = new javax.swing.JPanel();
        mainPanelPersonalInfo = new javax.swing.JPanel();
        lblPersonalInformation = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblReligion = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        lblContactNumber = new javax.swing.JLabel();
        txtContactNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnCancelPersonal = new javax.swing.JButton();
        btnNextStepPersonal = new javax.swing.JButton();
        cmbGender = new javax.swing.JComboBox<>();
        pillarDesignPanel = new javax.swing.JPanel();
        txtReligion = new javax.swing.JTextField();
        panelAcademicInfo = new javax.swing.JPanel();
        mainPanelAcademicInfo = new javax.swing.JPanel();
        lblAcademicInformation = new javax.swing.JLabel();
        lblGraduationYear = new javax.swing.JLabel();
        lblStrand = new javax.swing.JLabel();
        lblGeneralAverage = new javax.swing.JLabel();
        lblHonorsAwards = new javax.swing.JLabel();
        lblAchievements = new javax.swing.JLabel();
        txtGraduationYear = new javax.swing.JTextField();
        txtGeneralAverage = new javax.swing.JTextField();
        cmbStrand = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHonors = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAchievements = new javax.swing.JTextArea();
        btnBackAcademic = new javax.swing.JButton();
        btnNextAcademic = new javax.swing.JButton();
        pillarDesignPanel2 = new javax.swing.JPanel();
        lblSchoolName = new javax.swing.JLabel();
        txtSchoolName = new javax.swing.JTextField();
        panelProgramSelection = new javax.swing.JPanel();
        lblProgramSelection = new javax.swing.JLabel();
        lblChoose3Choices = new javax.swing.JLabel();
        lblFirstChoice = new javax.swing.JLabel();
        lblSecondChoice = new javax.swing.JLabel();
        lblThirdChoice = new javax.swing.JLabel();
        cmbProgramFirstChoice = new javax.swing.JComboBox<>();
        cmbProgramThirdChoice = new javax.swing.JComboBox<>();
        cmbProgramSecondChoice = new javax.swing.JComboBox<>();
        btnEnroll = new javax.swing.JButton();
        btnBackProgram = new javax.swing.JButton();
        pillaDesignPanel3 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(0, 51, 102));

        tabEnrollment.setBackground(new java.awt.Color(255, 255, 255));
        tabEnrollment.setForeground(new java.awt.Color(0, 51, 102));
        tabEnrollment.setAlignmentX(1.0F);

        panelPersonalInfo.setBackground(new java.awt.Color(255, 255, 255));

        mainPanelPersonalInfo.setBackground(new java.awt.Color(255, 255, 255));
        mainPanelPersonalInfo.setForeground(new java.awt.Color(0, 51, 102));

        lblPersonalInformation.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblPersonalInformation.setForeground(new java.awt.Color(0, 51, 102));
        lblPersonalInformation.setText("PERSONAL INFORMATION");

        lblAge.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblAge.setForeground(new java.awt.Color(0, 51, 102));
        lblAge.setText("Age");

        lblEmail.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 51, 102));
        lblEmail.setText("Email");

        lblFullName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(0, 51, 102));
        lblFullName.setText("Full Name");

        lblGender.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblGender.setForeground(new java.awt.Color(0, 51, 102));
        lblGender.setText("Gender");

        lblReligion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblReligion.setForeground(new java.awt.Color(0, 51, 102));
        lblReligion.setText("Religion");

        lblAddress.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(0, 51, 102));
        lblAddress.setText("Address");

        txtFullName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtFullName.setForeground(new java.awt.Color(0, 51, 102));

        txtAge.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtAge.setForeground(new java.awt.Color(0, 51, 102));
        txtAge.addActionListener(this::txtAgeActionPerformed);

        txtAddress.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(0, 51, 102));

        lblContactNumber.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblContactNumber.setForeground(new java.awt.Color(0, 51, 102));
        lblContactNumber.setText("Contact No.");

        txtContactNumber.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtContactNumber.setForeground(new java.awt.Color(0, 51, 102));

        txtEmail.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 51, 102));

        btnCancelPersonal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnCancelPersonal.setForeground(new java.awt.Color(0, 51, 102));
        btnCancelPersonal.setText("Cancel");

        btnNextStepPersonal.setBackground(new java.awt.Color(0, 51, 102));
        btnNextStepPersonal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnNextStepPersonal.setForeground(new java.awt.Color(255, 255, 255));
        btnNextStepPersonal.setText("Next >");
        btnNextStepPersonal.addActionListener(this::btnNextStepPersonalActionPerformed);

        cmbGender.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cmbGender.setForeground(new java.awt.Color(0, 51, 102));
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Prefer not to say" }));
        cmbGender.addActionListener(this::cmbGenderActionPerformed);

        pillarDesignPanel.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout pillarDesignPanelLayout = new javax.swing.GroupLayout(pillarDesignPanel);
        pillarDesignPanel.setLayout(pillarDesignPanelLayout);
        pillarDesignPanelLayout.setHorizontalGroup(
            pillarDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );
        pillarDesignPanelLayout.setVerticalGroup(
            pillarDesignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        txtReligion.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtReligion.setForeground(new java.awt.Color(0, 51, 102));
        txtReligion.addActionListener(this::txtReligionActionPerformed);

        javax.swing.GroupLayout mainPanelPersonalInfoLayout = new javax.swing.GroupLayout(mainPanelPersonalInfo);
        mainPanelPersonalInfo.setLayout(mainPanelPersonalInfoLayout);
        mainPanelPersonalInfoLayout.setHorizontalGroup(
            mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelPersonalInfoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pillarDesignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelPersonalInfoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelPersonalInfoLayout.createSequentialGroup()
                                .addComponent(lblPersonalInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(mainPanelPersonalInfoLayout.createSequentialGroup()
                                .addGroup(mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(111, 111, 111))
                            .addGroup(mainPanelPersonalInfoLayout.createSequentialGroup()
                                .addGroup(mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelPersonalInfoLayout.createSequentialGroup()
                                        .addGroup(mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(mainPanelPersonalInfoLayout.createSequentialGroup()
                                        .addGroup(mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelPersonalInfoLayout.createSequentialGroup()
                                                .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(230, 230, 230))
                                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(mainPanelPersonalInfoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelPersonal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNextStepPersonal)
                        .addGap(64, 64, 64))))
        );
        mainPanelPersonalInfoLayout.setVerticalGroup(
            mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelPersonalInfoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblPersonalInformation)
                .addGap(41, 41, 41)
                .addGroup(mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelPersonalInfoLayout.createSequentialGroup()
                        .addComponent(lblFullName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelPersonalInfoLayout.createSequentialGroup()
                        .addGroup(mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelPersonalInfoLayout.createSequentialGroup()
                                .addComponent(lblGender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelPersonalInfoLayout.createSequentialGroup()
                                .addComponent(lblAge)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelPersonalInfoLayout.createSequentialGroup()
                        .addComponent(lblReligion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelPersonalInfoLayout.createSequentialGroup()
                        .addComponent(lblAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                .addGap(20, 20, 20)
                .addGroup(mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(lblContactNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(mainPanelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNextStepPersonal)
                    .addComponent(btnCancelPersonal))
                .addGap(52, 52, 52))
            .addGroup(mainPanelPersonalInfoLayout.createSequentialGroup()
                .addComponent(pillarDesignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPersonalInfoLayout = new javax.swing.GroupLayout(panelPersonalInfo);
        panelPersonalInfo.setLayout(panelPersonalInfoLayout);
        panelPersonalInfoLayout.setHorizontalGroup(
            panelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanelPersonalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPersonalInfoLayout.setVerticalGroup(
            panelPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPersonalInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanelPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        tabEnrollment.addTab("1. Personal Information", panelPersonalInfo);

        mainPanelAcademicInfo.setBackground(new java.awt.Color(255, 255, 255));

        lblAcademicInformation.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblAcademicInformation.setForeground(new java.awt.Color(0, 51, 102));
        lblAcademicInformation.setText("ACADEMIC INFORMATION");

        lblGraduationYear.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblGraduationYear.setForeground(new java.awt.Color(0, 51, 102));
        lblGraduationYear.setText("Year Graduated ");

        lblStrand.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblStrand.setForeground(new java.awt.Color(0, 51, 102));
        lblStrand.setText("Track / Strand");

        lblGeneralAverage.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblGeneralAverage.setForeground(new java.awt.Color(0, 51, 102));
        lblGeneralAverage.setText("GWA");

        lblHonorsAwards.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblHonorsAwards.setForeground(new java.awt.Color(0, 51, 102));
        lblHonorsAwards.setText("Honors / Awards");

        lblAchievements.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblAchievements.setForeground(new java.awt.Color(0, 51, 102));
        lblAchievements.setText("Achievements");

        txtGraduationYear.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtGraduationYear.setForeground(new java.awt.Color(0, 51, 102));
        txtGraduationYear.addActionListener(this::txtGraduationYearActionPerformed);

        txtGeneralAverage.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtGeneralAverage.setForeground(new java.awt.Color(0, 51, 102));
        txtGeneralAverage.addActionListener(this::txtGeneralAverageActionPerformed);

        cmbStrand.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cmbStrand.setForeground(new java.awt.Color(0, 51, 102));
        cmbStrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STEM", "ABM", "HUMMS", "GAS", "TVL" }));
        cmbStrand.addActionListener(this::cmbStrandActionPerformed);

        txtHonors.setColumns(20);
        txtHonors.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtHonors.setForeground(new java.awt.Color(0, 51, 102));
        txtHonors.setRows(5);
        txtHonors.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtHonors);

        txtAchievements.setColumns(20);
        txtAchievements.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtAchievements.setForeground(new java.awt.Color(0, 51, 102));
        txtAchievements.setRows(5);
        jScrollPane2.setViewportView(txtAchievements);

        btnBackAcademic.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnBackAcademic.setForeground(new java.awt.Color(0, 51, 102));
        btnBackAcademic.setText("< Back");
        btnBackAcademic.addActionListener(this::btnBackAcademicActionPerformed);

        btnNextAcademic.setBackground(new java.awt.Color(0, 51, 102));
        btnNextAcademic.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnNextAcademic.setForeground(new java.awt.Color(255, 255, 255));
        btnNextAcademic.setText("Next >");
        btnNextAcademic.addActionListener(this::btnNextAcademicActionPerformed);

        pillarDesignPanel2.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout pillarDesignPanel2Layout = new javax.swing.GroupLayout(pillarDesignPanel2);
        pillarDesignPanel2.setLayout(pillarDesignPanel2Layout);
        pillarDesignPanel2Layout.setHorizontalGroup(
            pillarDesignPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        pillarDesignPanel2Layout.setVerticalGroup(
            pillarDesignPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblSchoolName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblSchoolName.setForeground(new java.awt.Color(0, 51, 102));
        lblSchoolName.setText("Graduated from");

        txtSchoolName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtSchoolName.setForeground(new java.awt.Color(0, 51, 102));
        txtSchoolName.addActionListener(this::txtSchoolNameActionPerformed);

        javax.swing.GroupLayout mainPanelAcademicInfoLayout = new javax.swing.GroupLayout(mainPanelAcademicInfo);
        mainPanelAcademicInfo.setLayout(mainPanelAcademicInfoLayout);
        mainPanelAcademicInfoLayout.setHorizontalGroup(
            mainPanelAcademicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelAcademicInfoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pillarDesignPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelAcademicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelAcademicInfoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(mainPanelAcademicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelAcademicInfoLayout.createSequentialGroup()
                                .addComponent(lblHonorsAwards)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAchievements)
                                .addGap(212, 212, 212))
                            .addGroup(mainPanelAcademicInfoLayout.createSequentialGroup()
                                .addGroup(mainPanelAcademicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSchoolName, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSchoolName)
                                    .addComponent(lblAcademicInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mainPanelAcademicInfoLayout.createSequentialGroup()
                                        .addGroup(mainPanelAcademicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblStrand)
                                            .addComponent(cmbStrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(53, 53, 53)
                                        .addGroup(mainPanelAcademicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblGraduationYear)
                                            .addGroup(mainPanelAcademicInfoLayout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(txtGraduationYear, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(45, 45, 45)
                                        .addGroup(mainPanelAcademicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtGeneralAverage)
                                            .addComponent(lblGeneralAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(mainPanelAcademicInfoLayout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 35, Short.MAX_VALUE))))
                    .addGroup(mainPanelAcademicInfoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBackAcademic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNextAcademic)
                        .addGap(92, 92, 92))))
        );
        mainPanelAcademicInfoLayout.setVerticalGroup(
            mainPanelAcademicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelAcademicInfoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblAcademicInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSchoolName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelAcademicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelAcademicInfoLayout.createSequentialGroup()
                        .addComponent(txtSchoolName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelAcademicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStrand, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGraduationYear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelAcademicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbStrand, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGraduationYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanelAcademicInfoLayout.createSequentialGroup()
                        .addComponent(lblGeneralAverage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGeneralAverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(mainPanelAcademicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAchievements)
                    .addComponent(lblHonorsAwards))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelAcademicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(mainPanelAcademicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNextAcademic)
                    .addComponent(btnBackAcademic))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(mainPanelAcademicInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pillarDesignPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelAcademicInfoLayout = new javax.swing.GroupLayout(panelAcademicInfo);
        panelAcademicInfo.setLayout(panelAcademicInfoLayout);
        panelAcademicInfoLayout.setHorizontalGroup(
            panelAcademicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanelAcademicInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelAcademicInfoLayout.setVerticalGroup(
            panelAcademicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAcademicInfoLayout.createSequentialGroup()
                .addComponent(mainPanelAcademicInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        tabEnrollment.addTab("2. Academic Information", panelAcademicInfo);

        panelProgramSelection.setBackground(new java.awt.Color(255, 255, 255));

        lblProgramSelection.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblProgramSelection.setForeground(new java.awt.Color(0, 51, 102));
        lblProgramSelection.setText("PROGRAM SELECTION ");

        lblChoose3Choices.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblChoose3Choices.setForeground(new java.awt.Color(0, 51, 102));
        lblChoose3Choices.setText("(choose 3 choices)");

        lblFirstChoice.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblFirstChoice.setForeground(new java.awt.Color(0, 51, 102));
        lblFirstChoice.setText("1st Choice");

        lblSecondChoice.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblSecondChoice.setForeground(new java.awt.Color(0, 51, 102));
        lblSecondChoice.setText("2nd Choice");

        lblThirdChoice.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblThirdChoice.setForeground(new java.awt.Color(0, 51, 102));
        lblThirdChoice.setText("3rd Choice");

        cmbProgramFirstChoice.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cmbProgramFirstChoice.setForeground(new java.awt.Color(0, 51, 102));
        cmbProgramFirstChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT", "BSIS", "Entrepreneurship", "Public Administration", "BSED Mathematics", "BSED Eghlish", " " }));
        cmbProgramFirstChoice.addActionListener(this::cmbProgramFirstChoiceActionPerformed);

        cmbProgramThirdChoice.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cmbProgramThirdChoice.setForeground(new java.awt.Color(0, 51, 102));
        cmbProgramThirdChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT", "BSIS", "Entrepreneurship", "Public Administration", "BSED Mathematics", "BSED Eghlish", " " }));
        cmbProgramThirdChoice.addActionListener(this::cmbProgramThirdChoiceActionPerformed);

        cmbProgramSecondChoice.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cmbProgramSecondChoice.setForeground(new java.awt.Color(0, 51, 102));
        cmbProgramSecondChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT", "BSIS", "Entrepreneurship", "Public Administration", "BSED Mathematics", "BSED Eghlish", " " }));
        cmbProgramSecondChoice.addActionListener(this::cmbProgramSecondChoiceActionPerformed);

        btnEnroll.setBackground(new java.awt.Color(0, 153, 0));
        btnEnroll.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnEnroll.setForeground(new java.awt.Color(255, 255, 255));
        btnEnroll.setText("Enroll");
        btnEnroll.addActionListener(this::btnEnrollActionPerformed);

        btnBackProgram.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnBackProgram.setForeground(new java.awt.Color(0, 51, 102));
        btnBackProgram.setText("< Back");
        btnBackProgram.addActionListener(this::btnBackProgramActionPerformed);

        pillaDesignPanel3.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout pillaDesignPanel3Layout = new javax.swing.GroupLayout(pillaDesignPanel3);
        pillaDesignPanel3.setLayout(pillaDesignPanel3Layout);
        pillaDesignPanel3Layout.setHorizontalGroup(
            pillaDesignPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        pillaDesignPanel3Layout.setVerticalGroup(
            pillaDesignPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelProgramSelectionLayout = new javax.swing.GroupLayout(panelProgramSelection);
        panelProgramSelection.setLayout(panelProgramSelectionLayout);
        panelProgramSelectionLayout.setHorizontalGroup(
            panelProgramSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProgramSelectionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pillaDesignPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelProgramSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProgramSelectionLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panelProgramSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProgramSelectionLayout.createSequentialGroup()
                                .addComponent(lblProgramSelection)
                                .addGap(58, 58, 58)
                                .addComponent(lblChoose3Choices))
                            .addComponent(lblSecondChoice)
                            .addGroup(panelProgramSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbProgramSecondChoice, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFirstChoice, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbProgramThirdChoice, javax.swing.GroupLayout.Alignment.LEADING, 0, 481, Short.MAX_VALUE)
                                .addComponent(lblThirdChoice, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbProgramFirstChoice, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(67, Short.MAX_VALUE))
                    .addGroup(panelProgramSelectionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBackProgram)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnroll)
                        .addGap(33, 33, 33))))
        );
        panelProgramSelectionLayout.setVerticalGroup(
            panelProgramSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProgramSelectionLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelProgramSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgramSelection)
                    .addComponent(lblChoose3Choices, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblFirstChoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbProgramFirstChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSecondChoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbProgramSecondChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblThirdChoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbProgramThirdChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(panelProgramSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackProgram)
                    .addComponent(btnEnroll))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(panelProgramSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pillaDesignPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabEnrollment.addTab("3. Program Selection", panelProgramSelection);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(tabEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tabEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextStepPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextStepPersonalActionPerformed
         // GET INPUTS
    String fullName = txtFullName.getText().trim();
    String age = txtAge.getText().trim();
    String gender = cmbGender.getSelectedItem().toString();
    String religion = txtReligion.getText().trim();
    String address = txtAddress.getText().trim();
    String contact = txtContactNumber.getText().trim();
    String email = txtEmail.getText().trim();

    // VALIDATIONS

    if (fullName.isEmpty()) {
        JOptionPane.showMessageDialog( this, "Full Name is required!");
        txtFullName.requestFocus();
        return;
    }

    if (age.isEmpty()) {
        JOptionPane.showMessageDialog(this,"Age is required!");
        txtAge.requestFocus();
        return;
    }
    
        // CHECK IF NUMBER
    try {

        int studentAge = Integer.parseInt(age);

        if (studentAge <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Invalid Age!"
            );

            return;
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Age must be a number!"
        );

        txtAge.requestFocus();

        return;
    }
    
     // =====================================================
    // GENDER VALIDATION
    // =====================================================

    if (gender.equals("Select Gender")) {

        JOptionPane.showMessageDialog(
                this,
                "Please select gender!"
        );

        return;
    }

    if (religion.isEmpty()) {
        JOptionPane.showMessageDialog(this,"Religion is required!");
        txtReligion.requestFocus();
        return;
    }

    if (address.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Address is required!");
        txtAddress.requestFocus();
        return;
    }

    if (contact.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Contact Number is required!");
        txtContactNumber.requestFocus();
        return;
    }
    
    // MUST BE 11 DIGITS
    if (!contact.matches("\\d{11}")) {

        JOptionPane.showMessageDialog(
                this,
                "Contact Number must be 11 digits!"
        );

        txtContactNumber.requestFocus();

        return;
    }

    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(this,"Email is required!");
        txtEmail.requestFocus();
        return;
    }
    
        if (!email.contains("@")) {

        JOptionPane.showMessageDialog(
                this,
                "Email must contain @"
        );

        txtEmail.requestFocus();

        return;
    }

    // SAVE TO DATASTORE

    DataStore.fullName = fullName;
    DataStore.age = age;
    DataStore.gender = gender;
    DataStore.religion = religion;
    DataStore.address = address;
    DataStore.contactNumber = contact;
    DataStore.email = email;

    // GO TO NEXT TAB

    tabEnrollment.setSelectedIndex(1);
    }//GEN-LAST:event_btnNextStepPersonalActionPerformed

    private void btnBackProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackProgramActionPerformed
        tabEnrollment.setSelectedIndex(1);
    }//GEN-LAST:event_btnBackProgramActionPerformed

    private void cmbProgramSecondChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProgramSecondChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProgramSecondChoiceActionPerformed

    private void cmbProgramThirdChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProgramThirdChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProgramThirdChoiceActionPerformed

    private void cmbProgramFirstChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProgramFirstChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProgramFirstChoiceActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
            // GET INPUTS
    String firstChoice = cmbProgramFirstChoice.getSelectedItem().toString();
    String secondChoice = cmbProgramSecondChoice.getSelectedItem().toString();
    String thirdChoice = cmbProgramThirdChoice.getSelectedItem().toString();

    // VALIDATIONS

    if (firstChoice.equals(secondChoice) || firstChoice.equals(thirdChoice) || secondChoice.equals(thirdChoice)) {
        JOptionPane.showMessageDialog(this,"Program choices must be different!");
        return;
    }

    // SAVE TO DATASTORE

    DataStore.firstChoice = firstChoice;
    DataStore.secondChoice = secondChoice;
    DataStore.thirdChoice = thirdChoice;
    
    
try {

    Connection conn = DBConnection.getConnection();

    String fullName = txtFullName.getText();

    String programfirstChoice = cmbProgramFirstChoice.getSelectedItem().toString();
    String programsecondChoice = cmbProgramSecondChoice.getSelectedItem().toString();
    String programthirdChoice = cmbProgramThirdChoice.getSelectedItem().toString();

    String status = "Enrolled";

    String sql = "INSERT INTO student(full_name, first_choice, second_choice, third_choice, status) VALUES (?, ?, ?, ?, ?)";

    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, fullName);
    pst.setString(2, firstChoice);
    pst.setString(3, secondChoice);
    pst.setString(4, thirdChoice);
    pst.setString(5, status);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Enrollment Successful!");

} catch (Exception e) {

    e.printStackTrace();

}
    // OPEN SUMMARY FRAME

    StudentDashboardFrame dashboard = new StudentDashboardFrame();
    dashboard.setVisible(true);
    dispose();

    }//GEN-LAST:event_btnEnrollActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void cmbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGenderActionPerformed

    private void txtSchoolNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSchoolNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSchoolNameActionPerformed

    private void btnNextAcademicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextAcademicActionPerformed
        // GET INPUTS
        String school = txtSchoolName.getText().trim();
        String strand = cmbStrand.getSelectedItem().toString();
        String average = txtGeneralAverage.getText().trim();
        String graduationYear = txtGraduationYear.getText().trim();
        String honors = txtHonors.getText().trim();
        String achievements = txtAchievements.getText().trim();

        // VALIDATIONS

        if (school.isEmpty()) {
            JOptionPane.showMessageDialog(this, "School Name is required!");
            txtSchoolName.requestFocus();
            return;
        }

        if (average.isEmpty()) {
            JOptionPane.showMessageDialog(this,"General Average is required!");
            txtGeneralAverage.requestFocus();
            return;
        }

        try {

            double avg =
            Double.parseDouble(average);

            // NOT LOWER THAN 75
            if (avg < 75) {

                JOptionPane.showMessageDialog(
                    this,
                    "GWA cannot be lower than 75!"
                );

                return;
            }

            // NOT HIGHER THAN 100
            if (avg > 100) {

                JOptionPane.showMessageDialog(
                    this,
                    "GWA cannot exceed 100!"
                );

                return;
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                this,
                "GWA must be a number!"
            );

            return;
        }

        if (graduationYear.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Graduation Year is required!");
            txtGraduationYear.requestFocus();
            return;
        }

        if (honors.isEmpty()) {
            JOptionPane.showMessageDialog( this,"Honors/Awards is required!");
            txtHonors.requestFocus();
            return;
        }

        if (achievements.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Achievements is required!");
            txtAchievements.requestFocus();
            return;
        }

        // SAVE TO DATASTORE

        DataStore.schoolName = school;
        DataStore.strand = strand;
        DataStore.generalAverage = average;
        DataStore.graduationYear = graduationYear;
        DataStore.honors = honors;
        DataStore.achievements = achievements;

        // NEXT TAB

        tabEnrollment.setSelectedIndex(2);
    }//GEN-LAST:event_btnNextAcademicActionPerformed

    private void btnBackAcademicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAcademicActionPerformed
        tabEnrollment.setSelectedIndex(0);
    }//GEN-LAST:event_btnBackAcademicActionPerformed

    private void cmbStrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStrandActionPerformed

    private void txtGeneralAverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneralAverageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneralAverageActionPerformed

    private void txtGraduationYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGraduationYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGraduationYearActionPerformed

    private void txtReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReligionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentEnrollmentFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackAcademic;
    private javax.swing.JButton btnBackProgram;
    private javax.swing.JButton btnCancelPersonal;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnNextAcademic;
    private javax.swing.JButton btnNextStepPersonal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbProgramFirstChoice;
    private javax.swing.JComboBox<String> cmbProgramSecondChoice;
    private javax.swing.JComboBox<String> cmbProgramThirdChoice;
    private javax.swing.JComboBox<String> cmbStrand;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAcademicInformation;
    private javax.swing.JLabel lblAchievements;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblChoose3Choices;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstChoice;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGeneralAverage;
    private javax.swing.JLabel lblGraduationYear;
    private javax.swing.JLabel lblHonorsAwards;
    private javax.swing.JLabel lblPersonalInformation;
    private javax.swing.JLabel lblProgramSelection;
    private javax.swing.JLabel lblReligion;
    private javax.swing.JLabel lblSchoolName;
    private javax.swing.JLabel lblSecondChoice;
    private javax.swing.JLabel lblStrand;
    private javax.swing.JLabel lblThirdChoice;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainPanelAcademicInfo;
    private javax.swing.JPanel mainPanelPersonalInfo;
    private javax.swing.JPanel panelAcademicInfo;
    private javax.swing.JPanel panelPersonalInfo;
    private javax.swing.JPanel panelProgramSelection;
    private javax.swing.JPanel pillaDesignPanel3;
    private javax.swing.JPanel pillarDesignPanel;
    private javax.swing.JPanel pillarDesignPanel2;
    private javax.swing.JTabbedPane tabEnrollment;
    private javax.swing.JTextArea txtAchievements;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtGeneralAverage;
    private javax.swing.JTextField txtGraduationYear;
    private javax.swing.JTextArea txtHonors;
    private javax.swing.JTextField txtReligion;
    private javax.swing.JTextField txtSchoolName;
    // End of variables declaration//GEN-END:variables
}
